### ISSUE TITLE
Failing assertion does'nt stop the test

### ISSUE THREAD

**Issue by feugy** [caolan/nodeunit#170]
Due to the assertWrapper() function (in the lib/types.js script), when an assert failed, the error is well reported, but the test doesn't stop.

It's a very strange behaviour regarding other test framework (in Node or even in other languages), which always stop the running test at the first error encountered.

It allows the programmer to order its assertion and avoid ifs and greedy operators.

  test.equal(1, myArray.length);
  test.equal('something', myArray[0].attr);

**Comment by jmenashe** [comment]
+1
Any updates on this?
