### ISSUE TITLE
Documentation and examples omit way too many details

### ISSUE THREAD

**Issue by doug65536** [caolan/nodeunit#238]
The examples in the example directory do things that are completely undocumented.

Every example in the documentation is a fragment of a few lines of a test.

Nothing says anywhere where the `test` variable came from.

You need to add a COMPLETE hello-world test to the documentation that runs one test that has one assertion, does all the necessary requires, calls `test.done()`, etc.

Show the directory structure of the module being tested and the test module. Show the command line to invoke the nodeunit testrunner and its arguments.

You say that the asserts come from the assert module. What? Does that mean that I have to `require('assert')` or what? This is an example of the documentation strategically leaving out important information. Do you think I care where the assert implementation came from? Do I need to know that? Is that a hint that I need to go look at the assert module documentation?

Your documentation claims to try to make it easy. You make it very hard because you leave out everything that YOU assume everybody knows.

One think you need to learn about documentation is that you *need to state the obvious*. Never leave anything that you think is "obvious" out of the documentation. What is obvious to you is not obvious to someone who hasn't used a node testing framework before.

**Comment by mreinstein** [comment]
fix the conflicts and resubmit; I'll merge it.
