### ISSUE TITLE
JUnit reporter does not output time

### ISSUE THREAD

**Issue by yamikuronue** [caolan/nodeunit#275]
The console output includes the time taken to run the tests; however, the junit output does not include the time attribute. It would be ideal if it could ouput the time per test, but time per suite is good enough. 

Time is an attribute on testsuites, testsuite, and testcase:
https://svn.jenkins-ci.org/trunk/hudson/dtkit/dtkit-format/dtkit-junit-model/src/main/resources/com/thalesgroup/dtkit/junit/model/xsd/junit-4.xsd

**Comment by mreinstein** [comment]
Hey! Sorry for the long delay in addressing this. I think this is fixed via https://github.com/caolan/nodeunit/commit/72e6563e57573a75c539b4086ec7025929edd900

if not, feel free to re-open this issue
