### ISSUE TITLE
No such module evals in node 0.12 and io.js

### ISSUE THREAD

**Issue by h2non** [caolan/nodeunit#291]
Since I upgrade to node 0.12 (also in iojs), the internal low-level module `evals` is not available, and I'm getting the following error trace:

```bash
>> Error: No such module: evals
>>   at Error (native)
>>   at Object.<anonymous> (/Users/h2non/projects/grunt-jade-i18n/node_modules/grunt-contrib-nodeunit/node_modules/nodeunit/lib/utils.js:14:22)
>>   at Module._compile (module.js:460:26)
>>   at Object.Module._extensions..js (module.js:478:10)
>>   at Module.load (module.js:355:32)
>>   at Function.Module._load (module.js:310:12)
>>   at Module.require (module.js:365:17)
```

Maybe it should infer the node version and try to load the `vm.Script` in `nodeunit/lib/utils.js` instead of the `process.binding` call

**Comment by shakeelmohamed** [comment]
+ 1

**Comment by ericmann** [comment]
+1

**Comment by jawshooah** [comment]
:+1: This is breaking tests all over.

**Comment by mreinstein** [comment]
I'll publish a new version to npm if you submit a good fix.

**Comment by h2non** [comment]
This issue only affect to `0.7.x` and lower versions. 
Therefore upgrade is required. 

Closing

**Comment by jefflembeck** [comment]
I'm running into this issue on 0.9.1 currently.

**Comment by mreinstein** [comment]
pull request to fix this is welcome!

**Comment by Strajk** [comment]
For me, not worked even in v0.11.16, working fine in v0.10.39
