### ISSUE TITLE
Load tests in sequence using concatSeries

### ISSUE THREAD

**Issue by felipou** [caolan/nodeunit#296]
In the utils module, in the modulePaths function, async.concat is used to process the paths of the tests to be executed when running nodeunit as a command line tool.

Is this by design? Because I believe the async.concatSeries function would be more appropriate in this case, since it would make the tests be executed in the order that they are passed to the command, which makes a lot more sense to me.

**Comment by johnnyman727** [comment]
For the record, we have the same issue on [the Tessel CLI](https://github.com/tessel/t2-cli/issues/557#issuecomment-232969903). This repo appears to be unmaintained so we're just going to fork for now.
