### ISSUE TITLE
Check and X on Windows

### ISSUE THREAD

**Issue by nycdotnet** [caolan/nodeunit#298]
Hi,

The check and X don't show properly on the Windows console - they just show as `?`, with no color.

Would you accept a pull request to replace them (on Windows only) with a green happy face and red x?  Alternatively, a green up arrow and red down arrow?

Thanks.

**Comment by nycdotnet** [comment]
For example:
![nodeunit-arrows](https://cloud.githubusercontent.com/assets/3755379/7865570/bf00edac-0537-11e5-832f-f483a09aa6f5.PNG)

**Comment by mreinstein** [comment]
@nycdotnet sorry for the reply delay. Yes I'd accept a PR for this provided it is simplistic.
