### ISSUE TITLE
Some reporters do not display assertion error message

### ISSUE THREAD

**Issue by ben-pushspring** [caolan/nodeunit#319]
Add in an assertion error for a test. If you run the test using the default reporter, the message will show up. 

If you run the test using the html reporter, then the message will fail to appear.

It appears that some of the reporters are using the AssertionError from the node assert module instead of the assert library.

**Comment by mreinstein** [comment]
PR welcome

**Comment by ben-pushspring** [comment]
Working on submitting one now :)

**Comment by mreinstein** [comment]
you da man, thx

**Comment by ben-pushspring** [comment]
Thanks for the quick turnaround!
