### ISSUE TITLE
issues with the _deepEqual algorithm

### ISSUE THREAD

**Issue by ghost** [caolan/nodeunit#325]
Hi! The _deepEqual you are using in this library have various bugs, and lacks support for a lot of features e.g. Map(), Set(), promises etc. I mentioned some of it here. 
https://github.com/Kflash/boogy#differences-between-boogy-and-nodejs-core-assert-module

**Comment by mreinstein** [comment]
@ghost can you explain a little bit what specific nodeunit problem you are having? There are like 50 different deepEquals implementations out there, all of them claiming to be the most complete. :)

**Comment by mreinstein** [comment]
lack of clarification or clear problem, closing
