### ISSUE TITLE
Tap dependency update to v11

### ISSUE THREAD

**Issue by exsilium** [caolan/nodeunit#350]
Can we have nodeunit pump the tap dep to v11 please? Thank you! 🙇

**Comment by mreinstein** [comment]
unfortunately this isn't possible at the moment. nodeunit support really, really old versions of node. tap v11 dropped support for older versions.

**Comment by exsilium** [comment]
Thanks @mreinstein! But what's the strategy here going forward from nodeunit perspective? I'd expect people stuck in legacy non-supported node versions are ok to lock themselves to a particular version of nodeunit as well. At some point the drop needs to happen, or not? Cheers! 🍻

**Comment by andy-ganchrow** [comment]
In the dependency tree of tap v10.7.3 is hoek v2.16.3 which apparently has a security vulnerability, so it would be great if this were resolved.

**Comment by brettz9** [comment]
A warning to that effect would be very helpful!

**Comment by mreinstein** [comment]
> A warning to that effect would be very helpful!

Yes, Caolan and I have been meaning to do that for a while. Finally done via ec2ea882bfb7976c91a25256f855c153594d1b8c, thanks for the reminder. 👍

**Comment by brodybits** [comment]
FYI update to tap 12 in PR #356 seems to pass old Node.js versions back to 0.12, though with a few ugly engine warnings.

**Comment by mreinstein** [comment]
closing since tap has moved on from v11
