### ISSUE TITLE
Add 'nodeunit --watch' command for auto-running of tests

### ISSUE THREAD

**Issue by caolan** [caolan/nodeunit#42]
This should allow the watching of both lib and test directories and re-run tests when any changes occur. Perhaps make use of mikeal's watch module? https://github.com/mikeal/watch

**Comment by mreinstein** [comment]
in the interests of keeping nodeunit simpler, use one of the many file watching tools out there, and invoke nodeunit from that. Here's a simple recipe based on `onchange`:

https://www.npmjs.com/package/onchange

which could be declared like this in `package.json`:

```javascript
"scripts": {
   "test": "nodeunit ./test",
   "watch:tests": "onchange 'assets/*.js' -- npm test"
}
```

invoked from the command line like so:

```bash
node watch:tests
```

this is just one example. You can write your own or use a different watcher.
